### ISSUE TITLE
app-shells/push EPREFX="${EPREFIX}" line 24

### ISSUE THREAD

**Issue by fedan** [vaeth/mv-overlay#10]
https://github.com/vaeth/mv-overlay/blob/bd0af3850e8a34fcf8fa3b48194763394c7dadcc/app-shells/push/push-3.1-r2.ebuild#L24
in src_install()
```
EPREFIX="${EPREFIX}"
     ^
EPREFX="${EPREFIX}"
```

**Comment by vaeth** [comment]
Thanks. Fixed.
