### ISSUE TITLE
support eselect-repository

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/mv-overlay#14]
Trying to add this overlay with https://wiki.gentoo.org/wiki/Eselect/Repository
but it fails with

```
sudo eselect repository enable 232
error: Martin: repository not in repositories.xml
```

**Comment by vaeth** [comment]
This is a copy of the repository with the address https://cgit.gentoo.org/user/mv.git
The latter is hosted by gentoo and appears for me also with eselect repository list under the name "mv", currently as number 255. Perhaps you tried the one which is called "martin". The latter seems to be broken. Perhaps the script which generates the repositories.xml has problems with the UTF-8 symbol in my name.

In any case, this is a bug of eselect-repository (or its server-side scripts), and I can do nothing about it.

**Comment by Alessandro-Barbieri** [comment]
Seems working now.
