### ISSUE TITLE
app-portage/eix-0.34.2 fails to build

### ISSUE THREAD

**Issue by skinkie** [vaeth/mv-overlay#18]
[meson-log.txt](https://github.com/vaeth/mv-overlay/files/4666733/meson-log.txt)
[build.log](https://github.com/vaeth/mv-overlay/files/4666734/build.log)

**Comment by vaeth** [comment]
Thanks for the report. The reason is an (upstream) eix bug with meson when protobuf and sqlite are used together. Should be fixed with app-portage/eix-0.34.3.
