### ISSUE TITLE
sci-geosciences/googleearth-7.3.3 fails to start (symbol lookup error)

### ISSUE THREAD

**Issue by jeandestouches** [vaeth/mv-overlay#22]
Hi,
i'm having trouble to run sci-geosciences/googleearth-7.3.3 (system = amd64/no-multilib/hardened)
Here is the output when ran from a terminal : 

``/opt/googleearth/googleearth-bin: symbol lookup error: /opt/googleearth/libQt5Gui.so.5: undefined symbol: _ZN10QArrayData11shared_nullE``

This is with USE="+bundled-qt"
If you need other information, let me know. Thanks.

**Comment by vaeth** [comment]
googleearth is not opensource and apparently no longer maintained by upstream. If some library version does not match precisely, it will not work. Perhaps I should remove it from the overlay, but I kept it in case it still works for somebody.
The upstream recommendation is to run the browser version from earth.google.com.

Closing as CANTFIX.

**Comment by jeandestouches** [comment]
Alright. Just so you know, you might eventually want to keep 7.1.8.3036-r3 or 7.3.0.3832-r3 as these ones works. Unfortunately, my system are so old that the web version makes the browser crashes. Well, I'll keep your working ebuild in my localrepo just in case.
