### ISSUE TITLE
Cannot sync mv

### ISSUE THREAD

**Issue by kanyck** [vaeth/mv-overlay#26]
```
#❯ LANG=C layman -s mv

 * Fetching remote list...
 * Fetch Ok

 * Syncing selected overlay(s)...
 * Running Git... # ( cd /var/lib/layman/mv  && /usr/bin/git pull )
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

 * Failure result returned from Git
 * 
 * Errors:
 * ------
 * Failed to sync overlay "mv".
 * Error was: Syncing overlay "mv" returned status 1!
 * db.sync()
 * 

 * CLI: Errors occurred processing action sync
 * 
 * Errors:
 * ------
 * Failed to sync overlay "mv".
 * Error was: Syncing overlay "mv" returned status 1!
 * db.sync()
```

**Comment by kanyck** [comment]
Also, /var/lib/layman/stuff/metadata/layout.conf is absent now...

**Comment by vaeth** [comment]
Not a bug of the mv overlay. metadata/layout.conf [does exist](https://github.com/vaeth/mv-overlay/tree/main/metadata), also in the gentoo [copy of the repository](https://gitweb.gentoo.org/user/mv.git/tree/metadata).

Something must be misconfigured on your side. The error message indicates that layman did not get the renaming of "master" to "main" (which is the new git standard, avoiding non-inclusive language). Maybe removing and re-adding the respository on your side might help. I do not know and cannot help further with that.

**Comment by kanyck** [comment]
JFYI: after re-adding the repository still had to `git switch` manually.... now it syncs.
