### ISSUE TITLE
tres

### ISSUE THREAD

**Issue by RayOfLight1** [vaeth/mv-overlay#28]
Please, replace 
https://github.com/vaeth/mv-overlay/blob/6227e955e9ca1544312804c258abc8231d7e8ef8/sci-geosciences/googleearth/Manifest#L5
With:

`DIST google-earth-pro-stable_7.3.4_amd64.deb 55949724 BLAKE2B a7d622efaf9092f1d58c98da8c63db2a36f38ead7dc90cf2c0f286ba4e8e7261004048d060428bfe320edf3f2e2f9ce327c0bcfe94a5fca58d55ee33621b4fc7 SHA512 7c7d708729104b46e6982c60e00e04d956f06d96db5975b6cc35e2d5a001c09af1131bca764047d47f8920243fe661af5a8d70c07a2e00acd626c8a1703a7643`

k tnx bye :)

**Comment by vaeth** [comment]
Fixed; thanks for pointing out. I had already given up on google-earth.
