### ISSUE TITLE
missing masters attribute

### ISSUE THREAD

**Issue by latot** [vaeth/mv-overlay#31]
Hi, I'm using the overlay, but when added with layman, emerge tells the next message:

```
emerge -auDNU --with-bdeps=y @world
!!! Repository 'mv' is missing masters attribute in '/var/lib/layman/mv/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
WARNING: One or more repositories have missing repo_name entries:

	/var/lib/layman/mv/profiles/repo_name

NOTE: Each repo_name entry should be a plain text file containing a
unique name for the repository on the first line.
```

Thx!

**Comment by vaeth** [comment]
Something must be wrong in your configuration. The attribute exists in the repository: https://github.com/vaeth/mv-overlay/blob/main/metadata/layout.conf

**Comment by latot** [comment]
mm, just to confirm, I run this:

```
layman -a mv
```

is that right? or I'm adding other repo?

**Comment by vaeth** [comment]
Layman is somewhat deprecated and perhaps unmaintained. I had reports that it tried to update the ”master” branch although that was renamed to “main” quite a while ago. So perhaps you have an ancient version of the repository.
I think that the recommended replacement for layman is app-eselect/eselect-repository, but I used neither since years.

**Comment by vaeth** [comment]
Thanks for pointing out. Indeed, it seems that the default branch on cgit.gentoo.org/anongit.gentoo.org was still master. I  hope that I changed it now to main successfully.

**Comment by vaeth** [comment]
It is very strange: It worked for 1 minute, and now the old config is back. I do not know how to change the default branch got git.gentoo.org/anongit.gentoo.org. Maybe it is impossible.

**Comment by vaeth** [comment]
Now it seems that I really succeeded with the renaming of the default branch.
