### ISSUE TITLE
bad app-shells/push for eix

### ISSUE THREAD

**Issue by RayOfLight1** [vaeth/mv-overlay#32]
Hello, my system upgraded to push-3.4-r1 from mv, leaving me with an usable eix-sync:
```
eix-sync
 * push.sh from https://github.com/vaeth/push/ is needed
```
 
If I downgrade to push-3.4 from official gentoo repo, eix-sync starts with:
```
eix-sync
 * Syncing all portage overlays
```

Please fix

**Comment by vaeth** [comment]
Neither a bug of push nor of eix nor of the mv overlay:
Gentoo installs intentionally a broken version of push and patches eix to work (only) with that broken version.
Use only the non-broken versions from the mv overlay, and there is no such problem.
