### ISSUE TITLE
app-shells/schily-tools file collisions

### ISSUE THREAD

**Issue by samis** [vaeth/mv-overlay#5]
I tried to install app-shells/schily-tools-2018.03.01 but I get file collisions with man-pages on  /usr/share/man/man3/fprintf.3 and /usr/share/man/man3/sprintf.3. Any chance you can fix this by not installing or renaming these files in the ebuild?

**Comment by vaeth** [comment]
Thanks for the report. I had missed these collisions, because on my system the "original" pages were installed uncompressed while the schily pages were installed compressed; hence portage's automatic collision detection missed them.
