### ISSUE TITLE
app-shells/push EPREFX="${EPREFIX}"

### ISSUE THREAD

**Issue by fedan** [vaeth/mv-overlay#8]
Hi!
This is correct?
May be EPREFIX="${EPREFIX}"
https://github.com/vaeth/push/blob/v3.1/Makefile#L2

**Comment by vaeth** [comment]
Oh, you are speaking about the ebuild and not about the line in the Makefile you cited.
Thanks, Yes, this will be fixed.
It might take a week or even much longer until I can push changes for reasons I do not want to explain now.

**Comment by vaeth** [comment]
fixed
