### ISSUE TITLE
Unable to emerge google-earth-pro-stable_7.3.2_amd64

### ISSUE THREAD

**Issue by cbxd** [vaeth/mv-overlay#9]
Hello,
I am unable to emerge googleearth. After a few retries, emerge still ends up with the following error:

!!! Fetched file: google-earth-pro-stable_7.3.2_amd64.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      56455100
!!! Expected: 56550942
Refetching... File renamed to '/usr/portage/distfiles/google-earth-pro-stable_7.3.2_amd64.deb._checksum_failure_.dyzilrpj'

It seems there is a checksum mismatch. Could you please have a look at it?

Regards,
Chris

**Comment by mgomersbach** [comment]
Just downloaded the source file and checked the manifest on size  and checksum in the repo. They do differ, so it's just a matter digesting a new hash and it should be done.

**Comment by cbxd** [comment]
Alright, thanks a lot.

**Comment by vaeth** [comment]
Thanks for the report and sorry for the delay. I am very busy currently.
I updated the Manifest .
